language: python

python:
  - 3.6

  - FLASK_ENV='testing'

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install pytest

script:
  - pytest --cov=app

after_success:
- coveralls
